# Generated by Django 5.0.9 on 2024-10-07 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
