# Generated by Django 5.0.9 on 2024-10-16 08:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, default="", null=True, verbose_name="Text"
            ),
        ),
    ]
